// <auto-generated />
using System;
using DataModels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShWeb.Migrations
{
    [DbContext(typeof(SHcx))]
    [Migration("20250223135226_AddSingleChapterModeToUserSettings")]
    partial class AddSingleChapterModeToUserSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataModels.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<int>("BaseQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("base_question_id");

                    b.Property<DateTime>("DateCreatedAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created_audit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsCorrectAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct_answer");

                    b.Property<DateTime>("LastUpdatedAudit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_audit");

                    b.HasKey("AnswerId")
                        .HasName("pk_answers");

                    b.HasIndex("BaseQuestionId")
                        .HasDatabaseName("ix_answers_base_question_id");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldName")
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.BaseQuestion", b =>
                {
                    b.Property<int>("BaseQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("base_question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BaseQuestionId"));

                    b.Property<DateTime>("DateCreatedAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created_audit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DiscriminatorRF")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("discriminator_rf");

                    b.Property<string>("Hint")
                        .HasColumnType("text")
                        .HasColumnName("hint");

                    b.Property<DateTime>("LastUpdatedAudit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_audit");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("question_type");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.HasKey("BaseQuestionId")
                        .HasName("pk_base_questions");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_base_questions_subject_id");

                    b.ToTable("base_questions", (string)null);

                    b.HasDiscriminator<string>("DiscriminatorRF").HasValue("BaseQuestion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataModels.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookName")
                        .HasColumnType("text")
                        .HasColumnName("book_name");

                    b.Property<int>("BookOrder")
                        .HasColumnType("integer")
                        .HasColumnName("book_order");

                    b.Property<int>("BookType")
                        .HasColumnType("integer")
                        .HasColumnName("book_type");

                    b.Property<bool>("HasSubSubject")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sub_subject");

                    b.Property<string>("HebrewBookName")
                        .HasColumnType("text")
                        .HasColumnName("hebrew_book_name");

                    b.HasKey("BookId")
                        .HasName("pk_books");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.DeletedRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("RecordJson")
                        .HasColumnType("text")
                        .HasColumnName("record_json");

                    b.Property<string>("TableName")
                        .HasColumnType("text")
                        .HasColumnName("table_name");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_deleted_records");

                    b.ToTable("deleted_records", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.ExamAnswer", b =>
                {
                    b.Property<int>("ExamAnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exam_answer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExamAnswerId"));

                    b.Property<int?>("AnswerCorrectnessLevel")
                        .HasColumnType("integer")
                        .HasColumnName("answer_correctness_level");

                    b.Property<int?>("AnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("answer_id");

                    b.Property<int?>("BaseQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("base_question_id");

                    b.Property<int>("ExamExecutionId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_execution_id");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("text")
                        .HasColumnName("text_answer");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("interval")
                        .HasColumnName("time_spent");

                    b.HasKey("ExamAnswerId")
                        .HasName("pk_exam_answers");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_exam_answers_answer_id");

                    b.HasIndex("BaseQuestionId")
                        .HasDatabaseName("ix_exam_answers_base_question_id");

                    b.HasIndex("ExamExecutionId")
                        .HasDatabaseName("ix_exam_answers_exam_execution_id");

                    b.ToTable("exam_answers", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.ExamExecution", b =>
                {
                    b.Property<int>("ExamExecutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exam_execution_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExamExecutionId"));

                    b.Property<int?>("BaseQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("base_question_id");

                    b.Property<double>("CachedExamScore")
                        .HasColumnType("double precision")
                        .HasColumnName("cached_exam_score");

                    b.Property<int>("CorrectAnswersNum")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers_num");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("ExamRepeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("exam_repeat_number");

                    b.Property<int>("ExamStatus")
                        .HasColumnType("integer")
                        .HasColumnName("exam_status");

                    b.Property<int>("ExamType")
                        .HasColumnType("integer")
                        .HasColumnName("exam_type");

                    b.Property<int>("FromSubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("from_subject_id");

                    b.Property<int>("PartiallyCorrectAnswersNum")
                        .HasColumnType("integer")
                        .HasColumnName("partially_correct_answers_num");

                    b.Property<int?>("PlanExamId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_exam_id");

                    b.Property<int>("QuestionsAnswered")
                        .HasColumnType("integer")
                        .HasColumnName("questions_answered");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("ToSubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("to_subject_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WrongAnswersNum")
                        .HasColumnType("integer")
                        .HasColumnName("wrong_answers_num");

                    b.HasKey("ExamExecutionId")
                        .HasName("pk_exam_executions");

                    b.HasIndex("BaseQuestionId")
                        .HasDatabaseName("ix_exam_executions_base_question_id");

                    b.HasIndex("FromSubjectId")
                        .HasDatabaseName("ix_exam_executions_from_subject_id");

                    b.HasIndex("PlanExamId")
                        .HasDatabaseName("ix_exam_executions_plan_exam_id");

                    b.HasIndex("ToSubjectId")
                        .HasDatabaseName("ix_exam_executions_to_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_exam_executions_user_id");

                    b.ToTable("exam_executions", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.ExamPlan", b =>
                {
                    b.Property<int>("ExamPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exam_plan_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExamPlanId"));

                    b.Property<int>("ExamFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("exam_frequency");

                    b.Property<int>("FromSubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("from_subject_id");

                    b.Property<int>("QuestionsAmount")
                        .HasColumnType("integer")
                        .HasColumnName("questions_amount");

                    b.Property<int>("SubSubjectNum")
                        .HasColumnType("integer")
                        .HasColumnName("sub_subject_num");

                    b.Property<int>("SubjectNum")
                        .HasColumnType("integer")
                        .HasColumnName("subject_num");

                    b.Property<int>("ToSubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("to_subject_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ExamPlanId")
                        .HasName("pk_plan_exams");

                    b.HasIndex("FromSubjectId")
                        .HasDatabaseName("ix_plan_exams_from_subject_id");

                    b.HasIndex("ToSubjectId")
                        .HasDatabaseName("ix_plan_exams_to_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_plan_exams_user_id");

                    b.ToTable("plan_exams", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.ForumComment", b =>
                {
                    b.Property<int>("ForumCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("forum_comment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForumCommentId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("DateCreatedAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created_audit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ForumQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("forum_question_id");

                    b.Property<DateTime>("LastUpdatedAudit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_audit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_comment_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ForumCommentId")
                        .HasName("pk_forum_comments");

                    b.HasIndex("ForumQuestionId")
                        .HasDatabaseName("ix_forum_comments_forum_question_id");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("ix_forum_comments_parent_comment_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_forum_comments_user_id");

                    b.ToTable("forum_comments", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.ForumQuestion", b =>
                {
                    b.Property<int>("ForumQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("forum_question_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ForumQuestionId"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<DateTime>("DateCreatedAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_created_audit")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ForumQuestionDescription")
                        .HasColumnType("text")
                        .HasColumnName("forum_question_description");

                    b.Property<string>("ForumQuestionText")
                        .HasColumnType("text")
                        .HasColumnName("forum_question_text");

                    b.Property<int>("ForumQuestionType")
                        .HasColumnType("integer")
                        .HasColumnName("forum_question_type");

                    b.Property<DateTime>("LastUpdatedAudit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_audit");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("views_count");

                    b.HasKey("ForumQuestionId")
                        .HasName("pk_forum_questions");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_forum_questions_subject_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_forum_questions_user_id");

                    b.ToTable("forum_questions", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int?>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<int?>("SubSubjectCount")
                        .HasColumnType("integer")
                        .HasColumnName("sub_subject_count");

                    b.Property<string>("SubjectName")
                        .HasColumnType("text")
                        .HasColumnName("subject_name");

                    b.HasKey("SubjectId")
                        .HasName("pk_subjects");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_subjects_book_id");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.SubjectText", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectTextContent")
                        .HasColumnType("text")
                        .HasColumnName("subject_text_content");

                    b.HasKey("SubjectId")
                        .HasName("pk_subject_texts");

                    b.ToTable("subject_texts", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserFullName")
                        .HasColumnType("text")
                        .HasColumnName("user_full_name");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataModels.Models.Question", b =>
                {
                    b.HasBaseType("DataModels.Models.BaseQuestion");

                    b.Property<int?>("SubjectId1")
                        .HasColumnType("integer")
                        .HasColumnName("subject_id1");

                    b.HasIndex("SubjectId1")
                        .HasDatabaseName("ix_base_questions_subject_id1");

                    b.HasDiscriminator().HasValue("Question");
                });

            modelBuilder.Entity("DataModels.Models.UserQuestion", b =>
                {
                    b.HasBaseType("DataModels.Models.BaseQuestion");

                    b.Property<int?>("OriginalQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("original_question_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("UserId1")
                        .HasColumnType("integer")
                        .HasColumnName("user_id1");

                    b.HasIndex("OriginalQuestionId")
                        .HasDatabaseName("ix_base_questions_original_question_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_base_questions_user_id");

                    b.HasIndex("UserId1")
                        .HasDatabaseName("ix_base_questions_user_id1");

                    b.HasDiscriminator().HasValue("UserQuestion");
                });

            modelBuilder.Entity("DataModels.Models.Answer", b =>
                {
                    b.HasOne("DataModels.Models.BaseQuestion", "BaseQuestion")
                        .WithMany("Answers")
                        .HasForeignKey("BaseQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_base_questions_base_question_id");

                    b.Navigation("BaseQuestion");
                });

            modelBuilder.Entity("DataModels.Models.BaseQuestion", b =>
                {
                    b.HasOne("DataModels.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_base_questions_subjects_subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataModels.Models.ExamAnswer", b =>
                {
                    b.HasOne("DataModels.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("fk_exam_answers_answers_answer_id");

                    b.HasOne("DataModels.Models.BaseQuestion", "BaseQuestion")
                        .WithMany()
                        .HasForeignKey("BaseQuestionId")
                        .HasConstraintName("fk_exam_answers_base_questions_base_question_id");

                    b.HasOne("DataModels.Models.ExamExecution", "ExamExecution")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("ExamExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_answers_exam_executions_exam_execution_id");

                    b.Navigation("Answer");

                    b.Navigation("BaseQuestion");

                    b.Navigation("ExamExecution");
                });

            modelBuilder.Entity("DataModels.Models.ExamExecution", b =>
                {
                    b.HasOne("DataModels.Models.BaseQuestion", "CurrentQuestion")
                        .WithMany()
                        .HasForeignKey("BaseQuestionId")
                        .HasConstraintName("fk_exam_executions_base_questions_base_question_id");

                    b.HasOne("DataModels.Models.Subject", "FromSubject")
                        .WithMany("ExamExecutions")
                        .HasForeignKey("FromSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_executions_subjects_from_subject_id");

                    b.HasOne("DataModels.Models.ExamPlan", "PlanExam")
                        .WithMany("ExamExecutions")
                        .HasForeignKey("PlanExamId")
                        .HasConstraintName("fk_exam_executions_plan_exams_plan_exam_id");

                    b.HasOne("DataModels.Models.Subject", "ToSubject")
                        .WithMany()
                        .HasForeignKey("ToSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exam_executions_subjects_to_subject_id");

                    b.HasOne("DataModels.Models.User", "User")
                        .WithMany("ExamExecutions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_executions_users_user_id");

                    b.Navigation("CurrentQuestion");

                    b.Navigation("FromSubject");

                    b.Navigation("PlanExam");

                    b.Navigation("ToSubject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModels.Models.ExamPlan", b =>
                {
                    b.HasOne("DataModels.Models.Subject", "FromSubject")
                        .WithMany()
                        .HasForeignKey("FromSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_exams_subjects_from_subject_id");

                    b.HasOne("DataModels.Models.Subject", "ToSubject")
                        .WithMany()
                        .HasForeignKey("ToSubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_exams_subjects_to_subject_id");

                    b.HasOne("DataModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_exams_users_user_id");

                    b.Navigation("FromSubject");

                    b.Navigation("ToSubject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModels.Models.ForumComment", b =>
                {
                    b.HasOne("DataModels.Models.ForumQuestion", "ForumQuestion")
                        .WithMany("Comments")
                        .HasForeignKey("ForumQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_comments_forum_questions_forum_question_id");

                    b.HasOne("DataModels.Models.ForumComment", "ParentComment")
                        .WithMany("Comments")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("fk_forum_comments_forum_comments_parent_comment_id");

                    b.HasOne("DataModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_comments_users_user_id");

                    b.Navigation("ForumQuestion");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModels.Models.ForumQuestion", b =>
                {
                    b.HasOne("DataModels.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("fk_forum_questions_subjects_subject_id");

                    b.HasOne("DataModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_forum_questions_users_user_id");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModels.Models.Subject", b =>
                {
                    b.HasOne("DataModels.Models.Book", "Book")
                        .WithMany("Subjects")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subjects_books_book_id");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("DataModels.Models.SubjectText", b =>
                {
                    b.HasOne("DataModels.Models.Subject", "Subject")
                        .WithOne("SubjectText")
                        .HasForeignKey("DataModels.Models.SubjectText", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subject_texts_subjects_subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DataModels.Models.User", b =>
                {
                    b.OwnsOne("DataModels.Models.UserSettings", "UserSettings", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<int>("DefaultQuestionCount")
                                .HasColumnType("integer")
                                .HasColumnName("user_settings_default_question_count");

                            b1.Property<int>("DefaultTimeExam")
                                .HasColumnType("integer")
                                .HasColumnName("user_settings_default_time_exam");

                            b1.Property<bool>("IsSingleChapterMode")
                                .HasColumnType("boolean")
                                .HasColumnName("user_settings_is_single_chapter_mode");

                            b1.Property<int>("MemoryLevel")
                                .HasColumnType("integer")
                                .HasColumnName("user_settings_memory_level");

                            b1.HasKey("UserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("DataModels.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DataModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DataModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("DataModels.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("DataModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DataModels.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("DataModels.Models.Question", b =>
                {
                    b.HasOne("DataModels.Models.Subject", null)
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId1")
                        .HasConstraintName("fk_base_questions_subjects_subject_id1");
                });

            modelBuilder.Entity("DataModels.Models.UserQuestion", b =>
                {
                    b.HasOne("DataModels.Models.Question", "Question")
                        .WithMany("DerivedUserQuestions")
                        .HasForeignKey("OriginalQuestionId")
                        .HasConstraintName("fk_base_questions_base_questions_original_question_id");

                    b.HasOne("DataModels.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_base_questions_asp_net_users_user_id");

                    b.HasOne("DataModels.Models.User", null)
                        .WithMany("UserQuestions")
                        .HasForeignKey("UserId1")
                        .HasConstraintName("fk_base_questions_asp_net_users_user_id1");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataModels.Models.BaseQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("DataModels.Models.Book", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("DataModels.Models.ExamExecution", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("DataModels.Models.ExamPlan", b =>
                {
                    b.Navigation("ExamExecutions");
                });

            modelBuilder.Entity("DataModels.Models.ForumComment", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DataModels.Models.ForumQuestion", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DataModels.Models.Subject", b =>
                {
                    b.Navigation("ExamExecutions");

                    b.Navigation("Questions");

                    b.Navigation("SubjectText");
                });

            modelBuilder.Entity("DataModels.Models.User", b =>
                {
                    b.Navigation("ExamExecutions");

                    b.Navigation("UserQuestions");
                });

            modelBuilder.Entity("DataModels.Models.Question", b =>
                {
                    b.Navigation("DerivedUserQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
